import { ConnectButton } from '@rainbow-me/rainbowkit';
import { AppProps } from 'next/app';
import Head from 'next/head'
import Image from 'next/image'
import AddTxButton from '../components/AddTxButton';
import styles from '../styles/Home.module.css'

// export default function Home(): AppProps {
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>JR Web3 Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{
        padding: 12,
        display: "flex",
        // alignItems: "right",
        justifyContent: "flex-end"
      }}
      >
        <ConnectButton label="Log in web3"
          accountStatus={{
            smallScreen: "avatar",
            largeScreen: "full",
          }}
          chainStatus={{
            smallScreen: "icon",
            largeScreen: "full",
          }}
          showBalance={{
            smallScreen: false,
            largeScreen: true,
          }}
        />
      </div>
      <main>
        <div style={{ padding: 40, color: 'blue' }}>
          <h3>Hola a todos</h3>
        </div>
        <div>
          <AddTxButton />
        </div>
      </main>
      <footer className={styles.footer}>
        Powered by{' '}
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>

      </footer>
    </div>

  )
}
