import { Heading } from "@chakra-ui/react";

const MyHeader = () => {
    return (
        <Heading>
            <title>JR Web3 Boilerplate</title>
            <meta name="description" content="Generated by create next app" />
            {/* <link rel="icon" href="/favicon.ico" /> */}
        </Heading>
    );
};

export default MyHeader;
