/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface TokensFactoryInterface extends utils.Interface {
  functions: {
    "createToken(string,string,uint256)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "createToken"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createToken",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "createToken",
    data: BytesLike
  ): Result;

  events: {
    "newContract(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "newContract"): EventFragment;
}

export interface newContractEventObject {
  newAddress: string;
}
export type newContractEvent = TypedEvent<[string], newContractEventObject>;

export type newContractEventFilter = TypedEventFilter<newContractEvent>;

export interface TokensFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TokensFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createToken(
      name_: PromiseOrValue<string>,
      symbol_: PromiseOrValue<string>,
      supply_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  createToken(
    name_: PromiseOrValue<string>,
    symbol_: PromiseOrValue<string>,
    supply_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createToken(
      name_: PromiseOrValue<string>,
      symbol_: PromiseOrValue<string>,
      supply_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "newContract(address)"(newAddress?: null): newContractEventFilter;
    newContract(newAddress?: null): newContractEventFilter;
  };

  estimateGas: {
    createToken(
      name_: PromiseOrValue<string>,
      symbol_: PromiseOrValue<string>,
      supply_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createToken(
      name_: PromiseOrValue<string>,
      symbol_: PromiseOrValue<string>,
      supply_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
